### ISSUE TITLE
Still workig?

### ISSUE THREAD

**Issue by Krankenkasse** [gamersi/chefkoch-api#1]
Hi, im wondering if this still works cause im only getting [] as result if i want to get the recipes of a category.

My code is:
```
const chefkoch = require('chefkoch-api');

chefkoch.chefkochAPI.getCategories().then(function(data){
    let category = data[2];
    console.log(category)
    chefkoch.chefkochAPI.getRecipes(category, 5, 0).then(function(data){
        console.log(data);
    });
});
```
And the Result:
```
Debugger attached.
Category { name: 'Cremes', url: '/rs/s0g52/Creme-Rezepte.html' }
[]
```
Greetings, Thomas.

**Comment by gamersi** [comment]
I will check it in the next few days and then I will give you feedback whether it works or not

**Comment by gamersi** [comment]
I found the Error and I am currently working on a fix. The error is that the baseURL contains a "/" at the end and it adds "/rs/...." to it so it has two slashes and that shows the 404 page.

**Comment by gamersi** [comment]
Update the package to version 1.1.2 and the issue should be resolved

**Comment by gamersi** [comment]
![image](https://user-images.githubusercontent.com/46320904/163343943-341c5594-175f-407c-87f3-8c49641b0337.png)
confirming it works
