### ISSUE TITLE
Use REST api instead of webscraping

### ISSUE THREAD

**Issue by wrzr123** [gamersi/chefkoch-api#11]
Hey,

is there a reason why you use webscraping instead of retrieving the recipes via the Chefkoch REST API?
In case the reason is that you didn't know about it, then I'm happy to help: https://api.chefkoch.de/v2/recipes/3435291511780260

I'm also starting to implement a Chefkoch API, so it would be interesting to know in case you have reasons why you want to use webscraping instead of the REST API.

Regards,
Jonas

**Comment by gamersi** [comment]
Is there a API documentation? I tried to figure it out but I did not find anything and other people are using webscraping as well. I found out that the Chefkoch website uses SSG(static site generation) thus does not need an API in the frontend
Regards

**Comment by wrzr123** [comment]
Nope, no documentation. The links you posted are quite old discussions, but I agree that Chefkoch probably doesn't like that the API is used. On the other hand, the same applies to scraping, and it would be fairly easy to block access to the API.
I think I'll go for the API for now. If that stops working, I can still switch to scraping.

**Comment by gamersi** [comment]
Ok but thanks for letting me know
